name:
  maximum: 50
email:
  maximum: 255
password:
  minimum: 6
remember:
  checked: "1"
  unchecked: "0"
avatar:
  resize: 50
  size: 80
  follow: 30
mail:
  to: "to@example.org"
  from: "noreply@example.com"
  expired: 2
micropost:
  max_length: 140
  capacity_of_picture: 5
  resize: 400
